name = "Ivan Huamani"
rol = "Flutter Developer"
email = "ivansaul.dev@gmail.com"
phone = "+51 964 834 771"
birthday = "March 26, 1996"
location = "Lima, Lima, Peru"
avatar = "https://i.imgur.com/l9zxVUh.png"
username = "ivansaul" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d249743.73289570768!2d-77.15258869060781!3d-12.026589994004635!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c5f619ee3ec7%3A0x14206cb9cc452e4a!2zTGltYSwgUGVyw7o!5e0!3m2!1ses-419!2sus!4v1686250682460!5m2!1ses-419!2sus" 
presentation = """
I am a passionate and self-taught mobile developer specializing in Flutter. My focus is on creating intuitive and aesthetically appealing mobile applications. Although I am new to the professional field, I have invested time and effort in building a strong foundation of knowledge in Flutter and Dart.

I am excited about opportunities for growth and learning, and I am ready to contribute to a dynamic team in the development of high-quality mobile applications.
"""
