############## Education config #################
#################################################
[[education]]
title = "National University of Engineering - UNI"
timeline = "2013 — 2018"
description = "Faculty of Geological, Mining, and Metallurgical Engineering"

[[education]]
title = "CEPS - UNI"
timeline = "2015 — 2016"
description = "Object-Oriented Programming with Python and C++"

[[education]]
title = "Python Web Scraping Bootcamp - Udemy"
timeline = "2016 — 2017"
description = "I completed a specialized bootcamp in Web Scraping, Web Crawling, and Web Automation. During the course, I acquired skills in data extraction from websites, automated navigation, and web content analysis using Python, Selenium, and BeautifulSoup."

[[education]]
title = "Flutter Mobile - Udemy"
timeline = "Dec 2022 - Feb 2023"
description = "During the course, I gained fundamental knowledge about Flutter architecture, user interface design, and the implementation of interactive features for iOS and Android, including their deployment in app stores."

[[education]]
title = "Flutter State Management with Riverpod/Bloc"
timeline = "Mar 2023 - Ongoing"
description = "I am dedicating time and effort to studying and developing skills in state management using the Riverpod and Bloc libraries in the context of Flutter."

############# Experience config #################
#################################################
[[experience]]
title = "Mining Planning - Buenaventura Mining Company"
timeline = "Nov 2018 — Aug 2019"
description = "I developed and created computer applications using Python in the mining software Minesight to automate block handling. Improved efficiency and precision in mining planning, reduced processing times, and minimized human errors."

[[experience]]
title = "Planning and Productivity - Volcan Mining Company"
timeline = "Sep 2019 — Sep 2021"
description = "During my time at the company, I played a key role in cost reduction by implementing effective measures to decrease explosives consumption in mining operations. My focus was on optimizing blasting processes by applying innovative techniques and efficient strategies."

[[experience]]
title = "Mine Operations Supervisor - Alpayana Mining Company"
timeline = "Oct 2021 — Jan 2023"
description = "In my role as a Mine Operations Supervisor, I had the responsibility of leading and coordinating the daily activities of the team of workers under my supervision. I worked closely with the production staff to ensure efficient and safe mining operations."

[[experience]]
title = "Junior Flutter Developer - NOA Experience Colombia"
timeline = "May 2023 — Present"
description = "During this time, I've learned to work with technologies like Riverpod, BLoC, Freezed, JsonSerializable, and I've delved into clean architecture, implemented animations, and worked with websockets and streams. Every day is an opportunity to grow and learn as I build solutions in the exciting world of mobile programming."

############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = false
show_value = false

[[skill]]
title = "Flutter"
value = "60%"

[[skill]]
title = "Python"
value = "70%"

[[skill]]
title = "Git"
value = "65%"

[[skill]]
title = "Dart"
value = "60%"

[[skill]]
title = "HTML/CSS"
value = "60%"

[[skill]]
title = "Figma"
value = "60%"

[[skill]]
title = "Adobe Illustrator"
value = "70%"


############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = false
show_value = false

[[language]]
title = "Spanish"
value = "100%"

[[language]]
title = "English"
value = "60%"

[[language]]
title = "Quechua"
value = "80%"